version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2


jobs:
  construccion_38:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/testing_pytest_circleci_0"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pytest --version
      - run: python code/main.py

  testing_38:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/testing_pytest_circleci_0"' >> $BASH_ENV
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pytest -vvv --cov test
      - codecov/upload

  construccion_39: ## fdgdf
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/testing_pytest_circleci_0"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pytest --version
      - run: python code/main.py

  testing_39:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/testing_pytest_circleci_0"' >> $BASH_ENV
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pytest -vvv test/test_main.py

workflows:
  construccion_testing_38:
    jobs:
      - construccion_38
      - testing_38:
          requires:
            - construccion_38

  construccion_testing_39:
    jobs:
      - construccion_39
      - testing_39:
          requires:
            - construccion_39